### ISSUE TITLE
error with geopoint

### ISSUE THREAD

**Issue by gerswin** [yahoohung/loopback-graphql-server#10]
Error: GeoPoint.lng field type must be Output Type but got: undefined.
 using 
  "location": {
      "type": "GeoPoint"
    }

in my model

**Comment by rungissan** [comment]
I have got the same problem. just try another approach  -  loopback-graphql-relay

**Comment by gerswin** [comment]
i found other issues with other projects, I can't remember right now.

**Comment by gerswin** [comment]
i just fixed

**Comment by gerswin** [comment]
https://github.com/gerswin/loopback-graphql-server

**Comment by devpascoe** [comment]
Strange ... i just npm installed and while i see the merge history should have applied the fix ... i got v1.1.8 BUT in src/types/GeoPoint/GeoPointType.js i still see

```
lng: {
  lng: new GraphQLNonNull(GraphQLFloat),
  resolve: obj => obj.lng
}
```

when i should be

```
lng: {
  type: new GraphQLNonNull(GraphQLFloat),
  resolve: obj => obj.lng
}
```

Instead i had to npm install --save git://github.com/yahoohung/loopback-graphql-server.git
and got the latest. Might need to simply push a new version number to npm.
